set(GLFW_ROOT ${CMAKE_CURRENT_LIST_DIR}/glfw)
set(GLFW_BUILD ${BUILD_DIRECTORY}/glfw)

set(GLFW_BUILD_DOCS OFF CACHE BOOL "" FORCE)
set(GLFW_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(GLFW_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)

set(GLFW_BUILD_WAYLAND OFF)
set(GLFW_BUILD_X11 ON)

add_subdirectory(${GLFW_ROOT} ${GLFW_BUILD})
