add_modules(${PROJECT_NAME}
	src/quark.ixx
	src/log/module.ixx
	src/log/loggers.ixx
	src/config/module.ixx
	src/config/os.ixx
	src/config/directories.ixx
	src/render/module.ixx
	src/render/window.ixx
	src/render/gl.ixx
	src/render/scene.ixx
	src/utility/module.ixx
	src/utility/clock.ixx
)

add_sources(${PROJECT_NAME}
	src/quark.cxx
	#src/render/window.cxx
)
